/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as PorraRouteImport } from './routes/porra'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PorraSettingsRouteImport } from './routes/porra.settings'
import { Route as PorraRankingRouteImport } from './routes/porra.ranking'
import { Route as PorraHomeRouteImport } from './routes/porra.home'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const PorraRoute = PorraRouteImport.update({
  id: '/porra',
  path: '/porra',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PorraSettingsRoute = PorraSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PorraRoute,
} as any)
const PorraRankingRoute = PorraRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => PorraRoute,
} as any)
const PorraHomeRoute = PorraHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PorraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/porra': typeof PorraRouteWithChildren
  '/start': typeof StartRoute
  '/porra/home': typeof PorraHomeRoute
  '/porra/ranking': typeof PorraRankingRoute
  '/porra/settings': typeof PorraSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/porra': typeof PorraRouteWithChildren
  '/start': typeof StartRoute
  '/porra/home': typeof PorraHomeRoute
  '/porra/ranking': typeof PorraRankingRoute
  '/porra/settings': typeof PorraSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/porra': typeof PorraRouteWithChildren
  '/start': typeof StartRoute
  '/porra/home': typeof PorraHomeRoute
  '/porra/ranking': typeof PorraRankingRoute
  '/porra/settings': typeof PorraSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/porra'
    | '/start'
    | '/porra/home'
    | '/porra/ranking'
    | '/porra/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/porra'
    | '/start'
    | '/porra/home'
    | '/porra/ranking'
    | '/porra/settings'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/porra'
    | '/start'
    | '/porra/home'
    | '/porra/ranking'
    | '/porra/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  PorraRoute: typeof PorraRouteWithChildren
  StartRoute: typeof StartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porra': {
      id: '/porra'
      path: '/porra'
      fullPath: '/porra'
      preLoaderRoute: typeof PorraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porra/settings': {
      id: '/porra/settings'
      path: '/settings'
      fullPath: '/porra/settings'
      preLoaderRoute: typeof PorraSettingsRouteImport
      parentRoute: typeof PorraRoute
    }
    '/porra/ranking': {
      id: '/porra/ranking'
      path: '/ranking'
      fullPath: '/porra/ranking'
      preLoaderRoute: typeof PorraRankingRouteImport
      parentRoute: typeof PorraRoute
    }
    '/porra/home': {
      id: '/porra/home'
      path: '/home'
      fullPath: '/porra/home'
      preLoaderRoute: typeof PorraHomeRouteImport
      parentRoute: typeof PorraRoute
    }
  }
}

interface PorraRouteChildren {
  PorraHomeRoute: typeof PorraHomeRoute
  PorraRankingRoute: typeof PorraRankingRoute
  PorraSettingsRoute: typeof PorraSettingsRoute
}

const PorraRouteChildren: PorraRouteChildren = {
  PorraHomeRoute: PorraHomeRoute,
  PorraRankingRoute: PorraRankingRoute,
  PorraSettingsRoute: PorraSettingsRoute,
}

const PorraRouteWithChildren = PorraRoute._addFileChildren(PorraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  PorraRoute: PorraRouteWithChildren,
  StartRoute: StartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
